apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcMetadata.name}}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    {{- range $key, $val := .Values.labels }}
      {{ $key }}: {{ $val }}
    {{- end }}
  type : {{ .Values.type }}
  ports:
  - name: ui
    port: {{ .Values.uiPort }}
    targetPort: {{ .Values.uiPort }}
    protocol: 
  - name: slave
    port: {{ .Values.slavePort }}
    protocol:
  - name: http
    port: {{ .Values.httpPort }}
    targetPort: {{ .Values.uiPort }}
    